version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
    groups:
      patch-updates:
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
